name: Update Devportal Documentation - Basic Requirements

on:
  push:
    paths:
      - 'docs/basic_requirements.md'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the triggering repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Copy or transform README to add frontmatter for Docusaurus
 
      - name: Transform basic_requirements.md for Docusaurus
        run: |
          mkdir transformed
          # Add header text and prepend it to basic_requirements.md
          echo "---" > transformed/basic_requirements.md
          echo "sidebar_position: 1" >> transformed/basic_requirements.md
          echo "title: Basic Requirements" >> transformed/basic_requirements.md
          echo "---" >> transformed/basic_requirements.md
          echo "" >> transformed/basic_requirements.md
          echo ":::info[Note]" >> transformed/basic_requirements.md
          echo "This content is automatically updated from the repository, in this case from the basic_requirements.md file." >> transformed/basic_requirements.md
          echo ":::" >> transformed/basic_requirements.md
          echo "" >> transformed/basic_requirements.md
          # Append the original basic_requirements.md content after the header text
          cat basic_requirements.md >> transformed/basic_requirements.md

      # Step 3: Clone the Docusaurus repository
      - name: Clone Docusaurus Repository
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
        run: |
          git clone https://ivegabr:${GITHUB_TOKEN}@github.com/ivegabr/docs-test.git
          cd docs-test
          git checkout -b update-from-repo1 || git checkout update-from-repo1
          cd ..

      # Step 4: Copy the transformed README to the Docusaurus `docs` folder
      - name: Copy basic_requirements.md to Docusaurus Repo
        run: |
          cp transformed/basic_requirements.md docs-test/docs/rif-relay/docs/basic_requirements.md

      # Step 5: Commit changes to the new branch in Docusaurus repository
      - name: Commit Changes
        run: |
          cd docs-test
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/rif-relay/docs/basic_requirements.md
          git commit -m "Automated update of basic_requirements.md from repo1"
          git push -f origin update-from-repo1

      # Step 6: Create a pull request in the Docusaurus repository

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
        run: |
          cd docs-test
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ivegabr/docs-test/pulls \
          -d '{"title":"Automated update of basic_requirements.md from repo1","body":"This PR updates the Docusaurus documentation with the latest basic_requirements.md from repo1.","head":"update-from-repo1","base":"main"}'
