name: Update Docusaurus Documentation

on:
  push:
    paths:
      - 'README.md'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the triggering repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Copy or transform README to make it compatible with Docusaurus, if necessary
 
      - name: Transform README for Docusaurus
        run: |
          mkdir transformed
          # Add header text and prepend it to README.md
          echo "---" > transformed/README.md
          echo "sidebar_position: 2" >> transformed/README.md
          echo "title: Introduction" >> transformed/README.md
          echo "---" >> transformed/README.md
          echo "" >> transformed/README.md
          echo "# Introduction" >> transformed/README.md
          echo "" >> transformed/README.md
          echo ":::info[Note]" >> transformed/README.md
          echo "This content is automatically updated from the repository, in this case from the README.md file. Notice that the links to other documents are working properly." >> transformed/README.md
          echo ":::" >> transformed/README.md
          echo "" >> transformed/README.md
          # Append the original README content after the header text
          cat README.md >> transformed/README.md

      # Step 3: Clone the Docusaurus repository
      - name: Clone Docusaurus Repository
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
        run: |
          git clone https://ivegabr:${GITHUB_TOKEN}@github.com/ivegabr/docs-test.git
          cd docs-test
          git checkout -b update-from-repo1 || git checkout update-from-repo1
          cd ..

      # Step 4: Copy the transformed README to the Docusaurus `docs` folder
      - name: Copy README to Docusaurus Repo
        run: |
          cp transformed/README.md docs-test/docs/rif-relay/readme.md

      # Step 5: Commit changes to the new branch in Docusaurus repository
      - name: Commit Changes
        run: |
          cd docs-test
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/rif-relay/readme.md
          git commit -m "Automated update of README from repo1"
          git push -f origin update-from-repo1

      # Step 6: Create a pull request in the Docusaurus repository

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_TOKEN }}
        run: |
          cd docs-test
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ivegabr/docs-test/pulls \
          -d '{"title":"Automated update of README from repo1","body":"This PR updates the Docusaurus documentation with the latest README from repo1.","head":"update-from-repo1","base":"main"}'
